### ISSUE TITLE
Implement a possibility to download different Formats without content-negotation

### ISSUE THREAD

**Issue by l00mi** [zazuko/trifid#13]
For a link on the website: Download as JSON-LD, Turtle, ...

**Comment by l00mi** [comment]
Just looked a bit around, but I guess finally the most common solution is to have the `.fileformat` at the end of the resource.

For json-ld in Wikipedia .jsonld is stated which is debatable. The rest is more or less clear with .xml .n3 .nt ... I would argue that we only deliver RDF formats and no "flattening" to .csv or similar.

**Comment by ktk** [comment]
`.jsonld` is the official filename extension, see [Wikipedia](https://en.wikipedia.org/wiki/JSON-LD)

**Comment by bergos** [comment]
Using a different URL would need a pointer to the original resource. `content-location` could be used. But also it could lead to collisions. I will implement it with a parameter `format`, which will be the file extension. As it's an API and not a header field, using `format` (and not `accept`) and the file extension (instead of the media type) should be OK.

**Comment by l00mi** [comment]
Works like a charm!
