### ISSUE TITLE
Latest versions not published to Dockerhub

### ISSUE THREAD

**Issue by patrickwyler** [zazuko/trifid#141]
Could you publish the latest versions on Dockerhub?

On Dockerhub the latest version is [2.3.7](https://hub.docker.com/layers/zazuko/trifid/2.3.7/images/sha256-054be137de701e0a0bc3f92924f5f211a4f4f7e28b57240de9807439be8bf1a4?context=explore) and on Github it's [v2.4.0](https://github.com/zazuko/trifid/releases/tag/v2.4.0).

![Difference](https://user-images.githubusercontent.com/23375188/218481418-b758e284-0b05-48dc-a621-f6db7b35eef3.png)

**Comment by patrickwyler** [comment]
Found this commit https://github.com/zazuko/trifid/commit/8ff3071ee11b711dd3a82a48aab5f3cdd539e439.. is there a reason for not updating Dockerhub too?

**Comment by ludovicm67** [comment]
Hi @patrickwyler! Thank you for opening an issue here.

We decided to move from Docker Hub to GitHub Container Registry, as Docker Hub took decisions that were going in the wrong decision in terms of security (they decided a that time to only allow one token for a whole account and not per image ; if one is leaking, then everything gets compromised). And this is one of many bad decisions that were taken by them at that time. Probably things changed since then (I really hope so).

Since we had this project on Docker Hub, maybe I can take some time to re-evaluate the current situation. But our new projects will not be published on Docker Hub.

One big advantage of using the GitHub Container Registry, is that it's automatically linked with the GitHub project, and the CI (GitHub Actions) is automatically providing temporarily credentials to push images.

Is there something that prevent you to use the images from the GitHub Container Registry?

**Comment by ktk** [comment]
That raises another question, can we somehow unpublish the stuff we had on Dockerhub?

As an outsider of a project I still check Dockerhub by default, because that's what the default config fetches. So I do see that people might miss the newer versions on GitHub if they don't pay attention.

**Comment by ludovicm67** [comment]
I think that if we unpublish things from the Docker Hub, then it might break some workloads for the people that are still using the image from there, and this is not something that we want.

I configured the CI pipeline to also push on the Docker Hub since Docker Hub changed their mind about the tokens in the good direction, but our other projects will only be pushed on the GitHub Container Registry.

I will close this issue now.
