### ISSUE TITLE
Investigate OOM issues on Lindas TEST

### ISSUE THREAD

**Issue by l00mi** [zazuko/trifid#144]
@ludovicm67 can you in one sentence document here what was the problem for future reference?

Then simply close the issue.

**Comment by ludovicm67** [comment]
The issue was coming from someone/something that was querying the full dataset periodically.
A lot of data was transferred (a bit less than 4G), and was using a lot of RAM, even by the use of streaming.
The `sparql-proxy` was trying to get the full output to show it in the logs.
The fix consisted of making sure that NodeJS streams are working as expected, and that we warn in the logs if the result is too big to be shown there.
