### ISSUE TITLE
Support for Bearer token authentication

### ISSUE THREAD

**Issue by mielvds** [zazuko/trifid#147]
Hi! Are there plans to add more authentication methods, in particular Bearer token authentication? 

Maybe this is more something for https://github.com/zazuko/trifid-handler-sparql or even [sparql-http-client](https://github.com/bergos/sparql-http-client). sparql-http-client supports it by setting a custom header, but I'm not sure this is propagated all the way to trifid.

**Comment by ludovicm67** [comment]
Hi @mielvds, thanks for your question!

Regarding the authentication, in general the way to go is to use [trifid-plugin-sparql-proxy](https://github.com/zazuko/trifid-plugin-sparql-proxy) mounted at `/query`.

Basic auth is supported by using the `sparqlEndpoint.username` and `sparqlEndpoint.password`.
But in your case, you will need to use `fetchOptions.headers` (see: https://github.com/zazuko/sparql-proxy#usage) to configure a Bearer token.

Then all Trifid plugins can be configured to use the `/query` endpoint, so that you don't have to provide/expose credentials.
