### ISSUE TITLE
All proxied requests are forwarded as POST

### ISSUE THREAD

**Issue by tpluscode** [zazuko/trifid#462]
I noticed that the sparql proxy forwards `POST` as well as `GET` as `POST` to the original service

I think this may have a negative impact on potential caching between trifid and the original endpoint. IMO, `GET` should be preserved by default

**Comment by ludovicm67** [comment]
The sparql-proxy plugin is also a plugin that aims to add support for some missing features from some endpoint solutions in order to have something that other plugins can trust ; sending requests as POST allows support for bigger SPARQL queries as payload.

Solutions like [varnish-post](https://github.com/zazuko/varnish-post) exists in case caching is an issue.

I will close this issue for now ; in case there are issues that come from this, we can always consider this in the future.
But I will prefer pushing for something robust and stable, like we have now.
