### ISSUE TITLE
Can't figure out how to run trifid with custom config

### ISSUE THREAD

**Issue by NielsHoffmann** [zazuko/trifid#54]
Hi, It's probably my poor understanding of node.js but I can't figure out how to run trifid with my own configuration.
I cloned the git repo and did a npm install. Then I can run the default trifid config with npm start. The sample (big bang theory) dataset shows up.
However in the readme a trifid script is mentioned that you can pass a custom config to. I try to run the dbpedia example from the tutorial.md but I can't find the trifid script and adding the --config parameter to npm start is not working?
Hope you can point me in the right direction...

**Comment by bergos** [comment]
@NielsHoffmann Yes, you are right, that's a node/npm thing. Here a quick step by step list to get it running from scratch.

1. create a folder matching project name
2. go into that folder an run `npm init` to create a `package.json` file
3. install trifid and add it as dependency using `npm install trifid --save` 
4. add a `start` property to the `scripts` object in the `package.json` with the value `trifid --config=my-config.json`
5. copy your config as `my-config.json` to the project folder
6. run `npm start`

Short explanation: When you install trifid as dependency, it will be installed in the `node_modules` folder and a link to the `server.js` is created at `node_modules/.bin/trifid`. Npm adds the `node_modules/.bin` folder to the path before it runs a script defined in the `package.json` file. That's why you can define the script just with `trifid --config=`.

**Comment by ktk** [comment]
I've recently created a minimal config for Wikidata, that might help to understand how the config looks like. Process is basically what Thomas described above.

Check out the attached zip, it contains:

- `package.json` that sets all dependencies for node & run scripts
- `config.json` for a "productive" use in case this would be running on the domain `wikidata.org`
- `config.local.json` for URI rewriting, which is always useful for development or cases like this one where one does not own the namespace
- `views` directory containing minimal HTML template files

Unzip it, run `npm install`. After that you can run the server, I recommend to test the local debug version: `npm run start-local-debug`

Now you should be able to connect to port 8080, try a Wikidata resource for example: http://localhost:8080/entity/Q701

Also you get a YASGUI SPARQL frontend here: http://localhost:8080/sparql/

Hope this helps
[trifid-wikidata.zip](https://github.com/zazuko/trifid/files/3596446/trifid-wikidata.zip)

**Comment by NielsHoffmann** [comment]
Thank you so much for the extra info. I got the wikidata example working and also my local ontology running of a local graphdb instance. I figured out that I needed to add the datasetBaseUrl property to rewrite the localhost:8080 part of the uri
