### ISSUE TITLE
Read http redirects from store and handle them

### ISSUE THREAD

**Issue by l00mi** [zazuko/trifid#99]
Based on http https://www.w3.org/TR/HTTP-in-RDF/

see the example https://s.zazuko.com/cqmS6B for Redirect, similar a `410 Gone` could be implemented.

Accept:
Trifid response with a redirect according to the triples defined in the triplestore.

**Comment by l00mi** [comment]
I see two different implementations, naively for every Request does also query if for the URI in question a HTTP-IN-RDF instruction is ready. That has a strong impact to performance as it needs for most Requests unecessary SPARQL queries.

Another approach, which I am in favor is that, at start all redirects are queried and cached in Memory. This would allow fast response, but the Cache is only updated once at start-up. This solution could be paired with a update intervall (once a day, or week). 

Finally not all HTTP "instructions" described in the database should be executed, I think we need to whitelist what is allowed.

**Comment by bergos** [comment]
Implementation:
- a new middleware is created
- the middleware will read the triplestore configuration from the central triplestore configuration

Not covered:
- caching (we create a separate issue for it)

**Comment by cristianvasquez** [comment]
I've created the new middleware: https://github.com/zazuko/trifid-handler-http-in-rdf , (private repo, with a provisory? name)

It's a middleware that was tested on top of trifid-handler-fetch. It works like this:

1. The triples are captured in a dataset
2. Matchers are applied to the dataset (in this case only one, `handleRedirects`)
3. If no matches apply, the results are serialized, otherwise the handlers are executed.

I haven't documented it yet, as I want to check if the interface is right. I forgot to make a pull request for the 'initial commit'

@bergos could you please review this? https://github.com/zazuko/trifid-handler-http-in-rdf/commit/59218f5ba6289fabf52d66fe9f8127c44c0ef855

**Comment by l00mi** [comment]
@ludovicm67 do we already have an instance pointing to lindas? then we could test with the example above.

**Comment by ludovicm67** [comment]
I will take care of deploying it today, so that we can test it.

**Comment by cristianvasquez** [comment]
A demo of the functionality is here: https://ld.zazuko.com/redirect/req

**Comment by cristianvasquez** [comment]
@bergos I changed the implementation to a SPARQL based one: https://github.com/zazuko/trifid-handler-http-in-rdf/blob/main/index.js

**Comment by cristianvasquez** [comment]
Thanks, the handler is now published in https://github.com/zazuko/trifid-handle-redirects
